[theme]
base = "light"
primaryColor = "#0C73B8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = $PORT
